services:
  baseful:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend-data:/app/data
      - /var/log/proxy:/var/log/proxy
      - ./caddy-data:/root/.local/share/caddy
      - .:/repo
    environment:
      - DB_PATH=/app/data/data.db
      - PORT=3000
      - PROXY_LOG_PATH=/var/log/proxy/proxy.log
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
      - "80:80"
      - "443:443"
      - "6432:6432"
    networks:
      - baseful-network
    restart: unless-stopped

networks:
  baseful-network:
    external: true
