services:
  baseful:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baseful
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend-data:/app/data
      - ./caddy-data:/root/.local/share/caddy
      - .:/repo
    environment:
      - DB_PATH=/app/data/data.db
      - PORT=3002
    env_file:
      - .env
    ports:
      - "3002:3002"
      - "6432:6432"
      # - "80:80"   # Uncomment these if you want to use a domain with SSL
      # - "443:443" # and port 80 is not used by another app
    networks:
      - baseful-network
    restart: unless-stopped

networks:
  baseful-network:
    external: true
